### ISSUE TITLE
Name change ?

### ISSUE THREAD

**Issue by fgallaire** [PierreRaybaut/formlayout#10]
@PierreRaybaut wrote `formlayout` as an utility for Spyder.

I think that a dead simple Python 2 and 3/QT 4 and 5 GUI lib is a benediction which could be useful for many little projects and successful of its own.

A new and sexiest name could be a plus.

**Comment by lesteve** [comment]
Suggestions more than welcome! Full disclosure, I don't have any good ones at the moment ...

**Comment by PierreRaybaut** [comment]
@fgallaire, @lesteve : The current name has the advantage of describing honestly and precisely the library features (it does not oversell it). After all, it's not an advanced high-level API to Qt... it's just a wrapper around QFormLayout, that's all. I'm really open to a name change (I'm not particularly proud of the "formlayout" name :smile:) but let's not forget that even if `formlayout` could indeed be useful to a lot of people, its scope is quite limited.

**Comment by fgallaire** [comment]
@PierreRaybaut I agree formlayout is a quite honest name about the limitations, but the result is a real GUI for a lot of little app.

At the beginning I was thinking at something like _EasyGUI_ or _SimpleGUI_, but this names aren't free.

Maybe something like _QForm_ is honest and shorter and most descriptive. But this is a good name only if formlayout doesn't become multi-backends.

**Comment by fgallaire** [comment]
_QuickForm_ could be a cool name

**Comment by PierreRaybaut** [comment]
I like _QuickForm_ too. This could even be shortened to _QForm_ as you suggested earlier but not for the same reason.

| Proposition | Project name | Python module name |
| --- | --- | --- |
| No.1 | QuickForm | `quickform` |
| No.2 | QForm | `qform` |

Judging by the raw Google results for those two project names, **QuickForm** would certainly have more visibility. But that's not necessarily a problem because people would probably search "python qform" instead.

The two names are quite available (especially on PyPI).

**Comment by fgallaire** [comment]
>  After all, it's not an advanced high-level API to Qt...

With #59 and #61 we made some progress in this direction ^^

**Comment by fgallaire** [comment]
**QuickForm** is chosen.
Organization here:
https://github.com/QuickForm

Question, is it QuickForm 1.0 or 2.0 ?

**Comment by PierreRaybaut** [comment]
Let's named it QuickForm 1.0, to really start fresh.
