### ISSUE TITLE
Dependency check fails with PyQt5

### ISSUE THREAD

**Issue by troyspencer** [PierreRaybaut/formlayout#87]
I have PyQt5 installed, but my os.environ['QT_API'] returns 'pyqt', erroneously classifying my PyQt version as PyQt4 and resulting in an ImportError when the following PyQt4 import inevitably fails. When I modified the check at the beginning of formlayout.py to attempt the PyQt5 imports instead, everything works perfectly, so this is a false positive failure.

**Comment by brendanholmes1** [comment]
I had the same issue with PyQt5 v5.9

**Comment by igrekus** [comment]
Is this project still maintained?

**Comment by igrekus** [comment]
I didn't quite understand the need for `os.environ` modification and the purpose of `_modname` variable, so I left them out. Also, added error on usage with Qt4 and PySide since PySide is deprecated by developers and I didn't see anyone still using Qt4 for quite some time.

The import should now work for both PyQt5 and PySide2 correctly.
